### ISSUE TITLE
  AobiChen - HW-1

### ISSUE THREAD

**Issue by aobichen** [kurotanshi/vue-quest-game#5]
https://github.com/aobichen/vue-question-game
心理測驗小遊戲，謝謝

**Comment by kurotanshi** [comment]
把題目整合到 `json` 檔這點很不錯，如果未來遇到需要跟後端串接 api 的時候，也是透過類似的方式處理。

不過比較可惜的是，在新增題目的時候，答案的數量被限制在四個了，還有就是新增題目與答案的時候，沒有加上驗證，也就是題目與答案全空白的時候也能新增，是比較明顯的問題。

在答題與分數計算方面沒有什麼問題，整體功能完成得很好。
