### ISSUE TITLE
Oscar-HW

### ISSUE THREAD

**Issue by oscarchang69** [kurotanshi/vue-quest-game#6]
github:
[https://github.com/oscarchang69/fivehex-vue-hw](https://github.com/oscarchang69/fivehex-vue-hw)

codepen:
[https://codepen.io/oscarchang69/pen/rqNwdy](https://codepen.io/oscarchang69/pen/rqNwdy)

**Comment by kurotanshi** [comment]
你的一樣有套 bootstrap，樣式看起來就是比我預設出得漂亮，而且還自己加了 `twinkle` 動畫 XD

整體來說，功能沒有什麼問題。

要說的話，就是在 HTML 裡面， `id` 這個屬性是唯一值，也就是說 `id="txt題目"` 只能給一個 tag 使用，雖然這跟 Vue.js 沒什麼關係，但也算是網頁開發重要的觀念。

另外，我發現到你的 `filtersQuestion` 跟 `currentQuest` 其實是一樣的內容，只是為了用 `v-for` 包裝，你特地用了陣列將 `currentQuest` 包起來，這裡你其實可以利用 `v-for="(item, index) in questions" v-show="questionIndex === index"` 的方式來做：

``` html
  <div class="quest" v-for="(item, index) in questions" v-show="questionIndex === index">
      <h3 :class="{BlinkStyle:checkSelected}">{{questionIndex+1}}. {{item.quest}}</h3>
      <template v-for="(option,idx) in item.options">
          <label>
              <input type="radio" v-model="item.selected" :value="option.value"> {{idx+1}} {{option.ans}}
          </label>
      </template>
  </div>
```

這樣可以少寫一個 `computed` 屬性，只是你的 `checkSelected` 就要改寫了。

在判斷邊界如 `btnNext` 、 `btnPre` 其實只要改成

``` javascript
  btnNext() {
      if (!this.isSelected()) return;

      if (this.questionIndex  < this.questions.length) {
          this.questionIndex = this.questionIndex + 1;
      }
  },
  btnPre() {
      if (this.questionIndex > 0) {
          this.questionIndex -= 1;
      }
  },
```

這樣程式的易讀性會更高。
大概就這樣，題目要求的功能都有完成，很好。
